---
title: "CSZ2026"
output: html_document
---

---
title: "ZF analysis"
author: "Hayden Simm"
date: "2026-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(purrr)
library(lme4)
library(lmerTest)
library(emmeans)
library(dplyr)
library(janitor)
library(car)
```

```{r}
zf <- read_csv("../Data/BPS_CELLCOUNT.csv")

zf <- zf %>%
  clean_names()

str(zf)
```

Selecting only one row per sumed value
```{r}
df_sum <- zf %>%
  group_by(plate, well, concentration_ug_l) %>%
  summarise(
    total_gfp = sum(total_gfp, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  filter(total_gfp != 0)
```

ggplot of total GFP using cell count at 10 dpf
```{r}
cellcount <- ggplot(
    df_sum,
    aes(
        x = factor(concentration_ug_l),
        y = log(total_gfp),
        fill = factor(concentration_ug_l)
    )
) +
    
    # raw datapoints
    geom_jitter(
        shape = 21,
        color = "black",
        size = 3,
        stroke = 0.6,
        width = 0.15,
        alpha = 0.8
    ) +
    
    # mean points
    stat_summary(
        fun = mean,
        geom = "point",
        shape = 21,
        fill = "black",
        color = "black",
        size = 3,
        stroke = 1
    ) +
    
    # mean ± SE
    stat_summary(
        fun.data = mean_se,
        geom = "errorbar",
        width = 0.2,
        color = "black"
    ) +
    
    scale_fill_brewer(palette = "Greens") +
    
    labs(
        x = "BPS Concentration (µg/L)",
        y = "log (GFP intensity)",
        fill = "BPS Concentration (µg/L)"
    ) +
    
    theme_bw()

plot(cellcount)
```

```{r}
ggsave(
  filename = "../Figures/cellcount_plot.png",
  plot = cellcount,
  width = 8,
  height = 4,
  dpi = 300
)
```

the following code isn't complete and needs the ZF_analysis file run before
```{r}
heart_rate <- zf %>%
  select(concentration_ug_l, heart_rate_bpm) %>%
  filter(!is.na(heart_rate_bpm)) %>%
  mutate(concentration_ug_l = factor(concentration_ug_l))
```

```{r}
heart_plot<-ggplot(heart_rate, aes(x = concentration_ug_l, y = heart_rate_bpm, fill= factor(concentration_ug_l))) +
  
  # mean points
    stat_summary(
        fun = mean,
        geom = "point",
        shape = 21,
        fill = "black",
        color = "black",
        size = 3,
        stroke = 1
    ) +
  
 # mean ± SE
    stat_summary(
        fun.data = mean_se,
        geom = "errorbar",
        width = 0.2,
        color = "black"
    ) +
  
 # raw datapoints
    geom_jitter(
        shape = 21,
        color = "black",
        size = 3,
        stroke = 0.6,
        width = 0.15,
        alpha = 0.8
    ) +
  
  scale_fill_brewer(palette = "Greens") +
  
  labs(
    x = "BPS Concentration (µg/L)",
    y = "Heart rate (bpm)"
  ) +
  
  theme_bw()

plot(heart_plot)
```

```{r}
ggsave(
  filename = "../Figures/heart_rate.png",
  plot = heart_plot,
  width = 8,
  height = 4,
  dpi = 300
)
```

```{r}
hatched_plot <- ggplot(
  hatched,
  aes(
    x = concentration_ug_l,
    y = hatched_dpf,
    fill = factor(concentration_ug_l)
  )
) +
  
  geom_jitter(
    shape = 21,
    color = "black",
    width = 0.15,
    height = 0.05,
    alpha = 0.6,
    size = 2,
    stroke = 0.5
  ) +
  
  scale_y_continuous(breaks = c(2, 3, 4)) +
  
  scale_fill_brewer(palette = "Greens") +
  
  labs(
    x = "BPS Concentration (µg/L)",
    y = "Day hatched (dpf)",
    fill = "BPS Concentration (µg/L)"
  ) +
  
  theme_classic()

plot(hatched_plot)
```

```{r}
ggsave(
  filename = "../Figures/hatched.png",
  plot = hatched_plot,
  width = 8,
  height = 4,
  dpi = 300
)
```